# Use CodeClimate to help enforce style guides and maintainability
# metrics. You can either configure CodeClimate via:
#  * this file (https://docs.codeclimate.com/docs/advanced-configuration)
#  * via the interface @ codeclimate.com (in which case you should delete this file)
