language: android
android:
  components:
    # Enables latest revision of Android SDK Tools to be used
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-28
branches:
  only: 
    - master